"""empty message

Revision ID: 45610c0b638b
Revises: 52599d9efc6c
Create Date: 2019-12-17 15:38:36.165835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45610c0b638b'
down_revision = '52599d9efc6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_unique_constraint(None, 'statuses', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statuses', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
