"""empty message

Revision ID: 52599d9efc6c
Revises: a2469ad1e8eb
Create Date: 2019-12-17 15:08:42.851613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52599d9efc6c'
down_revision = 'a2469ad1e8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('desc', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'desc')
    # ### end Alembic commands ###
